### ISSUE TITLE
RangeError: toFixed() digits argument must be between 0 and 100

### ISSUE THREAD

**Issue by Memoi** [kemargrant/c4d#16]
Hi,

I have this error 13 times today between 9 AM and 7 PM:

RangeError: toFixed() digits argument must be between 0 and 100
    at Number.toFixed (<anonymous>)
    at CryptoBot.engine.Arbitrage [as binanceArbitrage] (D:\wal\TEST\c4d-master\c4d-master\engines\binance.js:78:93)
    at WebSocket.client.onmessage (D:\wal\TEST\c4d-master\c4d-master\engines\binance.js:752:10)
    at WebSocket.onMessage (D:\wal\TEST\c4d-master\c4d-master\node_modules\ws\lib\EventTarget.js:99:16)
    at emitOne (events.js:116:13)
    at WebSocket.emit (events.js:211:7)
    at Receiver._receiver.onmessage (D:\wal\TEST\c4d-master\c4d-master\node_modules\ws\lib\WebSocket.js:141:47)
    at Receiver.dataMessage (D:\wal\TEST\c4d-master\c4d-master\node_modules\ws\lib\Receiver.js:389:14)
    at perMessageDeflate.decompress (D:\wal\TEST\c4d-master\c4d-master\node_modules\ws\lib\Receiver.js:349:40)
    at _decompress (D:\wal\TEST\c4d-master\c4d-master\node_modules\ws\lib\PerMessageDeflate.js:306:9)

And only with this conf :

"pair1":"vet_btc",
"pair2":"btc_usdt",
"pair3":"vet_usdt",

Thanks for your help

**Comment by kemargrant** [comment]
Do you have any other log output?

**Comment by Memoi** [comment]
There is some log outside of the console ?
There is only this in the console

**Comment by kemargrant** [comment]
No there is not, but this wouldn't be the only output.
